CALTERAH_STATISTIC_ROOT = $(CALTERAH_COMMON_ROOT)/statistic

CALTERAH_STATISTIC_CSRCDIR = $(CALTERAH_STATISTIC_ROOT)
CALTERAH_STATISTIC_ASMSRCDIR = $(CALTERAH_STATISTIC_ROOT)

# find all the source files in the target directories
CALTERAH_STATISTIC_CSRCS = $(call get_csrcs, $(CALTERAH_STATISTIC_CSRCDIR))
CALTERAH_STATISTIC_ASMSRCS = $(call get_asmsrcs, $(CALTERAH_STATISTIC_ASMSRCDIR))

# get object files
CALTERAH_STATISTIC_COBJS = $(call get_relobjs, $(CALTERAH_STATISTIC_CSRCS))
CALTERAH_STATISTIC_ASMOBJS = $(call get_relobjs, $(CALTERAH_STATISTIC_ASMSRCS))
CALTERAH_STATISTIC_OBJS = $(CALTERAH_STATISTIC_COBJS) $(CALTERAH_STATISTIC_ASMOBJS)

# get dependency files
CALTERAH_STATISTIC_DEPS = $(call get_deps, $(CALTERAH_STATISTIC_OBJS))


# genearte library
CALTERAH_STATISTIC_LIB = $(OUT_DIR)/lib_calterah_statistic.a

COMMON_COMPILE_PREREQUISITES += $(CALTERAH_STATISTIC_ROOT)/statistic.mk

# library generation rule
$(CALTERAH_STATISTIC_LIB): $(CALTERAH_STATISTIC_OBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(CALTERAH_STATISTIC_OBJS)

# specific compile rules
# user can add rules to compile this library
# if not rules specified to this library, it will use default compiling rules
.SECONDEXPANSION:
$(CALTERAH_STATISTIC_COBJS): $(OUT_DIR)/%.o : %.c $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $< -o $@

.SECONDEXPANSION:
$(CALTERAH_STATISTIC_ASMOBJS): $(OUT_DIR)/%.o : %.s $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(ASM_OPT) $< -o $@

CALTERAH_COMMON_CSRC += $(CALTERAH_STATISTIC_CSRCS)
CALTERAH_COMMON_ASMSRCS += $(CALTERAH_STATISTIC_ASMSRCS)

CALTERAH_COMMON_COBJS += $(CALTERAH_STATISTIC_COBJS)
CALTERAH_COMMON_ASMOBJS += $(CALTERAH_STATISTIC_ASMOBJS)

CALTERAH_COMMON_LIBS += $(CALTERAH_STATISTIC_LIB)
