CALTERAH_CAN_UDS_ROOT = $(CALTERAH_COMMON_ROOT)/can_uds

CALTERAH_CAN_UDS_CSRCDIR = $(CALTERAH_CAN_UDS_ROOT)
CALTERAH_CAN_UDS_ASMSRCDIR = $(CALTERAH_CAN_UDS_ROOT)

# find all the source files in the target directories
CALTERAH_BM_UDS_ROOT = $(CALTERAH_ROOT)/baremetal/uds
CALTERAH_CAN_UDS_CSRCS = $(call get_csrcs, $(CALTERAH_CAN_UDS_CSRCDIR))
CALTERAH_CAN_UDS_CSRCS += $(CALTERAH_BM_UDS_ROOT)/services.c
CALTERAH_CAN_UDS_CSRCS += $(CALTERAH_BM_UDS_ROOT)/routine.c
CALTERAH_CAN_UDS_ASMSRCS = $(call get_asmsrcs, $(CALTERAH_CAN_UDS_ASMSRCDIR))

# get object files
CALTERAH_CAN_UDS_COBJS = $(call get_relobjs, $(CALTERAH_CAN_UDS_CSRCS))
CALTERAH_CAN_UDS_ASMOBJS = $(call get_relobjs, $(CALTERAH_CAN_UDS_ASMSRCS))
CALTERAH_CAN_UDS_OBJS = $(CALTERAH_CAN_UDS_COBJS) $(CALTERAH_CAN_UDS_ASMOBJS)

# get dependency files
CALTERAH_CAN_UDS_DEPS = $(call get_deps, $(CALTERAH_CAN_UDS_OBJS))


# genearte library
CALTERAH_CAN_UDS_LIB = $(OUT_DIR)/lib_calterah_can_uds.a

COMMON_COMPILE_PREREQUISITES += $(CALTERAH_CAN_UDS_ROOT)/can_uds.mk

# library generation rule
$(CALTERAH_CAN_UDS_LIB): $(CALTERAH_CAN_UDS_OBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(CALTERAH_CAN_UDS_OBJS)

# specific compile rules
# user can add rules to compile this library
# if not rules specified to this library, it will use default compiling rules
.SECONDEXPANSION:
$(CALTERAH_CAN_UDS_COBJS): $(OUT_DIR)/%.o : %.c $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $< -o $@

.SECONDEXPANSION:
$(CALTERAH_CAN_UDS_ASMOBJS): $(OUT_DIR)/%.o : %.s $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(ASM_OPT) $< -o $@

CALTERAH_COMMON_CSRC += $(CALTERAH_CAN_UDS_CSRCS)
CALTERAH_COMMON_ASMSRCS += $(CALTERAH_CAN_UDS_ASMSRCS)

CALTERAH_COMMON_COBJS += $(CALTERAH_CAN_UDS_COBJS)
CALTERAH_COMMON_ASMOBJS += $(CALTERAH_CAN_UDS_ASMOBJS)

CALTERAH_COMMON_LIBS += $(CALTERAH_CAN_UDS_LIB)
