#ifndef ALPS_OTP_MMAP_H
#define ALPS_OTP_MMAP_H

#define OTP_MMAP_SEC_BASE   (REL_REGBASE_EFUSE + 0x0140)
#define OTP_TRIM_AUX_ADC    (REL_REGBASE_EFUSE + 0x0158)
#define OTP_TRIM_RF_BIST    (REL_REGBASE_EFUSE + 0x015C)
#define OTP_TRIM_TEMP_SENSOR_HIGH   (REL_REGBASE_EFUSE + 0x0160)
#define OTP_TRIM_TEMP_SENSOR_LOW    (REL_REGBASE_EFUSE + 0x0164)
#define OTP_PART_NO         (REL_REGBASE_EFUSE + 0x00E0)
#define OTP_CHIP_VER        (REL_REGBASE_EFUSE + 0x00E4)

#endif
