CALTERAH_CUSTOM_ROOT = $(CALTERAH_COMMON_ROOT)/custom

CALTERAH_CUSTOM_CSRCDIR = $(CALTERAH_CUSTOM_ROOT)
CALTERAH_CUSTOM_ASMSRCDIR = $(CALTERAH_CUSTOM_ROOT)

# find all the source files in the target directories
CALTERAH_CUSTOM_CSRCS = $(call get_csrcs, $(CALTERAH_CUSTOM_CSRCDIR))
CALTERAH_CUSTOM_ASMSRCS = $(call get_asmsrcs, $(CALTERAH_CUSTOM_ASMSRCDIR))

# get object files
CALTERAH_CUSTOM_COBJS = $(call get_relobjs, $(CALTERAH_CUSTOM_CSRCS))
CALTERAH_CUSTOM_ASMOBJS = $(call get_relobjs, $(CALTERAH_CUSTOM_ASMSRCS))
CALTERAH_CUSTOM_OBJS = $(CALTERAH_CUSTOM_COBJS) $(CALTERAH_CUSTOM_ASMOBJS)

# get dependency files
CALTERAH_CUSTOM_DEPS = $(call get_deps, $(CALTERAH_CUSTOM_OBJS))


# genearte library
CALTERAH_CUSTOM_LIB = $(OUT_DIR)/lib_calterah_custom.a

COMMON_COMPILE_PREREQUISITES += $(CALTERAH_CUSTOM_ROOT)/custom.mk

# library generation rule
$(CALTERAH_CUSTOM_LIB): $(CALTERAH_CUSTOM_OBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(CALTERAH_CUSTOM_OBJS)

# specific compile rules
# user can add rules to compile this library
# if not rules specified to this library, it will use default compiling rules
.SECONDEXPANSION:
$(CALTERAH_CUSTOM_COBJS): $(OUT_DIR)/%.o : %.c $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $< -o $@

.SECONDEXPANSION:
$(CALTERAH_CUSTOM_ASMOBJS): $(OUT_DIR)/%.o : %.s $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(ASM_OPT) $< -o $@

CALTERAH_COMMON_CSRC += $(CALTERAH_CUSTOM_CSRCS)
CALTERAH_COMMON_ASMSRCS += $(CALTERAH_CUSTOM_ASMSRCS)

CALTERAH_COMMON_COBJS += $(CALTERAH_CUSTOM_COBJS)
CALTERAH_COMMON_ASMOBJS += $(CALTERAH_CUSTOM_ASMOBJS)

CALTERAH_COMMON_LIBS += $(CALTERAH_CUSTOM_LIB)

include $(CALTERAH_CUSTOM_ROOT)/user/user.mk
CALTERAH_INC_DIR += $(CALTERAH_CUSTOM_ROOT)/user


